# Generated by Django 3.2.14 on 2022-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incityobject',
            options={'ordering': ['id'], 'verbose_name': 'объект', 'verbose_name_plural': 'объект в городе'},
        ),
        migrations.AlterModelOptions(
            name='outcityobject',
            options={'ordering': ['id'], 'verbose_name': 'Загородный объект', 'verbose_name_plural': 'Загородный объект'},
        ),
        migrations.AlterModelOptions(
            name='outcityobjecttype',
            options={'ordering': ['id'], 'verbose_name': 'Тип загородного объекта', 'verbose_name_plural': 'Тип загородного объекта'},
        ),
        migrations.AddField(
            model_name='incityobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='incityobject',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='если хотите видеть на главной странице', verbose_name='горячий вариант'),
        ),
        migrations.AlterField(
            model_name='outcityobjecttype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тип загородного объекта'),
        ),
    ]
