# Generated by Django 3.2.14 on 2022-08-12 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20220810_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balcony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Балкон')),
            ],
            options={
                'verbose_name': 'Балкон',
                'verbose_name_plural': 'Балкон',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='изображение')),
                ('description', models.CharField(max_length=55, verbose_name='описание изображения')),
                ('note', models.CharField(max_length=55, verbose_name='примечание')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображение',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок статьи')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='текст статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статья',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='outcityobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='incityobject',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Основное изображение'),
        ),
    ]
