# Generated by Django 3.2.14 on 2022-08-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20220812_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphics',
            options={'ordering': ['id'], 'verbose_name': 'графический объект', 'verbose_name_plural': 'Графика'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='incityobject',
            name='balcony',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='agency.balcony', verbose_name='балкон'),
        ),
        migrations.AlterField(
            model_name='balcony',
            name='title',
            field=models.CharField(default='нет данных', max_length=100, verbose_name='Балкон'),
        ),
    ]
