# Generated by Django 3.2.14 on 2022-08-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20220812_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incityobject',
            name='balcony',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='agency.balcony', verbose_name='балкон'),
        ),
    ]
