# Generated by Django 3.2.14 on 2022-08-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_incityobject_balcony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balcony',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Балкон'),
        ),
    ]
