# Generated by Django 3.2.14 on 2022-08-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20220813_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcityobject',
            name='slug',
            field=models.SlugField(default='no_slug1', max_length=150, unique=True, verbose_name='URL'),
        ),
    ]
