# Generated by Django 3.2.14 on 2022-08-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20220813_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('galleryLink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.incityobject', verbose_name='Ссылка на объект')),
            ],
            options={
                'verbose_name': 'фото объекта',
                'verbose_name_plural': 'фото объекта',
                'ordering': ['galleryLink'],
            },
        ),
    ]
