# Generated by Django 3.2.14 on 2022-08-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20220818_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphics',
            options={'ordering': ['id'], 'verbose_name': 'графический объект', 'verbose_name_plural': 'Графика и т.п.'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
    ]
