# Generated by Django 3.2.14 on 2022-08-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20220818_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='note',
            field=models.TextField(blank=True, verbose_name='примечание'),
        ),
    ]
