# Generated by Django 3.2.14 on 2022-08-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0016_outcityobjecttype_in_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image2', models.ImageField(blank=True, upload_to='images', verbose_name='Фото')),
                ('note2', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('galleryLink2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.outcityobject', verbose_name='Ссылка на объект')),
            ],
            options={
                'verbose_name': 'фото объекта',
                'verbose_name_plural': 'фото загородного объекта',
                'ordering': ['galleryLink2'],
            },
        ),
    ]
