# Generated by Django 3.2.14 on 2022-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_incityobjecttype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcityobjecttype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='иконка(картинка) для типа объекта'),
        ),
        migrations.AlterField(
            model_name='incityobjecttype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='иконка(картинка) для типа объекта'),
        ),
    ]
